### ISSUE TITLE
Support parsing intervals from strings

### ISSUE THREAD

**Issue by omus** [invenia/Intervals.jl#116]
It would be very nice to have `parse(::Type{Interval{T}}, ::AbstractString)` which could take strings of the form `"[1,2)"`. I expect we'll need to provide the element type so that we can determine how we should parse the endpoint values.

One tricky part of this will be to determine where the delimiter is as `,` or `..` could be used in the endpoint value. Possibly in scenarios where it is ambiguous we should require quotes around the value.

**Comment by samuel-massinon** [comment]
Do you have any idea when this feature will be available? Is someone planning on working on this soon?

**Comment by omus** [comment]
No one is working on this currently but it would probably take 2-3 days to implement. Let me know if this should be prioritized

**Comment by samuel-massinon** [comment]
It's not a high priority, we have a way to work around it and it should be easy enough to switch to using this feature when this is done. Just would be nice to have.

**Comment by samuel-massinon** [comment]
Change of plans. The change we want to have involves a bunch of tests, metrics, etc and I think it would be a bunch of unnecessary work to have to do that twice. We are holding off on our changes until this is done.

**Comment by omus** [comment]
Thanks for letting me know. Should be able to work on this the week of July 6th

**Comment by omus** [comment]
Currently being registered but will be available in 1.4.0
