### ISSUE TITLE
isbounded() and isunbounded() are not exported

### ISSUE THREAD

**Issue by LakshyaKhatri** [invenia/Intervals.jl#125]
Thanks @omus for a quick response on the previous issue. Also, in the API section [(Intervals.span — Function)](https://invenia.github.io/Intervals.jl/latest/#Intervals.span) I have two doubts:
 1. The `isbounded` and `isunbounded` functions are not exported. Is that the expected behaviour? If so, it will be helpful to mention that in the docs.
 2. Is that trailing **( ` )** intentional in the second snippet?
![Screenshot from 2020-06-29 22-53-41](https://user-images.githubusercontent.com/28972442/86037043-6d326c00-ba5c-11ea-851e-4716c54725a9.png)

Feel free to close the issue if this is expected.

**Comment by omus** [comment]
Thanks for the issue. At the moment `isbounded` and `isunbounded` aren't exported as we will be changing `isopen` to no longer be exported (see https://github.com/invenia/Intervals.jl/pull/100)

The extra backtick is incorrect and should be corrected

**Comment by LakshyaKhatri** [comment]
let me know if you need help with the core library. I'm open to contributions.
