### ISSUE TITLE
Add to docstrings HourEnding and HourBegining have default inclusivity

### ISSUE THREAD

**Issue by oxinabox** [invenia/Intervals.jl#77]
To me it seems like a natural assumption that
`HourEnding` would have inclusivity of `false, true`,
and `HourBeginning` would have inclusivity of `true, false`

but I am not sure if I am typical or not.

**Comment by nickrobinson251** [comment]
Makes sense to me. And isn't it already the case? 
```julia
julia> using Intervals, Dates

julia> HourEnding(DateTime(2017, 02, 28, 06))
AnchoredInterval{-1 hour,DateTime}(2017-02-28T06:00:00, Inclusivity(false, true))

julia> HourBeginning(DateTime(2017, 02, 28, 06))
AnchoredInterval{1 hour,DateTime}(2017-02-28T06:00:00, Inclusivity(true, false))

(tmp.BCUQL3co) pkg> status Intervals
    Status `/private/var/folders/hx/1h0bbkfd18d4n1qrnwmrl4j00000gn/T/tmp.BCUQL3co/Project.toml`
  [d8418881] Intervals v0.5.1
```

**Comment by oxinabox** [comment]
we should add it to the docstrings....

**Comment by nickrobinson251** [comment]
yes, could be said in words

it is there in the examples https://github.com/invenia/Intervals.jl/blob/6010f10020c00aec3ddc54344dc1b0c6f44e4840/src/anchoredinterval.jl#L33-L58
